# Generated by Django 6.0.2 on 2026-02-19 05:29

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Recipes',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=250)),
                ('prep_time', models.DurationField(default=datetime.timedelta(seconds=7200))),
                ('difficulty', models.IntegerField(choices=[(1, 'Easy'), (2, 'Medium'), (3, 'Hard')])),
                ('vegitarian', models.BooleanField()),
                ('Description', models.CharField(max_length=5000)),
                ('Recipe_img', models.ImageField(upload_to='recipe/')),
            ],
        ),
    ]
